spring:
  application:
    name: smsservice

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}
  address: 0.0.0.0

twilio:
  account:
    sid: ${TWILIO_SID}
  auth:
    token: ${TWILIO_TOKEN}
  phone:
    number: "+19599911699"

app:
  download:
    url: ${APP_URL}